In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [142]:
from faker import Faker
from random import random
from sklearn.datasets import make_classification

import pandas as pd
import numpy as np
import csv
import random

In [143]:
fake = Faker()

In [144]:
# changing column data with faker

accounts_list = ['Savings', 'Current']
sex_list = ['Male', 'Female']
# names_list = [fake.name_female(), fake.name_male()]

# Fake Data Generator function
 
def fake_data():
    return{'Name': fake.name(), 
           'Gender': random.choice(sex_list),
           'Address': fake.street_address(), 
           'Nationality': 'Zimbabwean', 
           'Account_Type': random.choice(accounts_list), 
           'Age': random.randint(0, 2), 
           'Education': random.random() > 0.5, 
           'Employment': random.randint(0, 2),
           'Salary': random.randint(0, 2),
           'Employer_Stability': random.random() > 0.5,
           'Consistency': random.random() > 0.5,
           'Balance': random.randint(0, 2),
           'Residential_Status': random.random() > 0.5
          }


df = pd.DataFrame([fake_data() for _ in range(100000)], columns = ['Name', 'Gender', 'Address', 'Nationality', 'Account_Type', 'Age','Education', 'Employment', 'Salary', 'Employer_Stability', 'Consistency', 'Balance', 'Residential_Status'])
df.index.names = ['Customer_ID']

In [146]:
df.head()

,Name,Gender,Address,Nationality,Account_Type,Age,Education,Employment,Salary,Employer_Stability,Consistency,Balance,Residential_Status
Customer_ID,,,,,,,,,,,,,
0,Michelle Anderson,Male,630 Andrea Island Apt. 990,Zimbabwean,Savings,1,False,2,0,True,False,2,True
1,Mary Owens,Female,0854 Vasquez River,Zimbabwean,Current,2,True,0,1,False,False,1,False
2,Anna Cooper,Male,8443 Rodriguez Manors,Zimbabwean,Savings,2,False,2,1,True,True,0,True
3,Paul Davis,Male,380 Franco Isle,Zimbabwean,Savings,0,True,2,0,False,True,2,False
4,Sergio Clark,Female,605 White Gateway,Zimbabwean,Current,2,True,2,1,True,False,0,True

In [147]:
# Creates ['Service_Level'] column with either 0 for Silver, 1 for Gold or 2 for Platinum Level 

df['Service_Level'] = np.where((df['Age']==1)&(df['Education']==True)&(df['Employment']==2)&(df['Salary']==0)&(df['Employer_Stability']==False)&(df['Consistency']==True)&(df['Balance']==0)&(df['Residential_Status']==False), 0,
                               (np.where((df['Age']==1)&(df['Education']==True)&(df['Employment']==2)&(df['Salary']==2)&(df['Employer_Stability']==False)&(df['Consistency']==True)&(df['Balance']==2)&(df['Residential_Status']==True), 2, 1)))

In [150]:
# rows where Service_Level is not 0

df[df['Service_Level'] == 2]

,Name,Gender,Address,Nationality,Account_Type,Age,Education,Employment,Salary,Employer_Stability,Consistency,Balance,Residential_Status,Service_Level
Customer_ID,,,,,,,,,,,,,,
1015,Matthew Charles,Female,19679 Pitts Curve,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
2811,David Lloyd,Male,532 Henry Cove Suite 898,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
4018,Frank Wong,Female,5396 Kyle Parkway Apt. 403,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
4929,Amber King,Male,1793 Gary Highway,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
7998,James Adams,Female,52931 Tyler Port,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
8224,Jaime Davis,Male,841 Catherine Crescent Suite 460,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
9501,Max Jackson,Female,053 West Parkways,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
9542,Pedro Baker,Female,5004 Petty Hills Apt. 324,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
11592,Travis Patel,Female,043 Meyers Turnpike,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
11844,Savannah Watkins,Female,695 Jeffrey Brooks Suite 495,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
13556,John Beltran,Male,7423 Scott Shore,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
15245,Lisa Parker,Male,06717 Rangel Flats,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
16252,Sierra Hunt,Male,23848 Jeremiah Turnpike Suite 097,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
16731,James Gonzales,Male,7178 Hernandez Manor,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
18299,Jason Hill,Male,71368 Stephen Terrace Apt. 467,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
18521,Connie Gomez,Male,208 Anthony View,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
19601,Amy Hill,Male,8103 Sandra Fork Apt. 347,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
20275,Kimberly Cook,Male,47632 Mason Harbor,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
22381,Jennifer Atkins,Male,533 Brandon Avenue Suite 116,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
23121,Danny Mccoy,Male,8937 Mccoy Falls,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
23450,Andrew Jackson,Female,1200 Fuller Knoll Suite 221,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
23526,Toni Black,Male,5287 Thompson Square,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
24726,Patricia Lewis,Male,666 Bryce Port Suite 454,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
27955,Jennifer Norton,Male,606 Mary Via,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
33165,Dr. Brandon Flowers,Female,711 Smith Summit Apt. 204,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
33430,Kenneth Baldwin,Female,51244 Johnathan Views,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
34040,Darryl Oneill,Male,745 Bruce Glens Suite 880,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
35986,Michael Smith,Male,188 Kline Junction Suite 790,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
37824,Shawn Hill,Male,96805 Perez Drive,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
38472,Matthew Romero,Male,54417 Samantha Isle,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65518,Shawn Wilcox,Male,5665 Thomas Tunnel,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
68208,Samuel Beard,Male,7377 Brandon Course Suite 336,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
69036,Mrs. Tammy Ballard,Male,686 Matthew Parkways,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
69579,Melissa Wells,Female,010 Little Forks,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
70972,Carla Meyer,Female,811 Carpenter Course,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
75510,Antonio Johnson,Female,631 Kevin Lane,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
77095,Cynthia Powell,Male,890 Peter Rapid Apt. 691,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
79778,Andrea Rice,Male,288 Morris Falls,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
80106,Jeremy Griffin,Female,300 Carolyn Prairie,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
80268,Eric Oneal,Male,640 Tammy Valleys Suite 959,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
80871,Curtis Myers,Male,2716 Carter Overpass,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
81208,Loretta Collins,Female,505 Mcclain Crescent Apt. 234,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
81872,Andrew Proctor,Male,9217 Jennifer Lodge Suite 331,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
82539,Dean Gutierrez,Female,8069 Andrew Plains,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
83503,David Cohen,Female,5270 Ashley Center,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
83548,Eric Gaines,Female,519 Cunningham Knolls Apt. 108,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
85388,Jeffrey Ellison,Female,283 Carol Manor,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
86142,Lisa Tran,Male,139 Nguyen Fields Suite 877,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
87376,Eric Rocha,Female,386 Raymond Turnpike Suite 917,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
88895,Amanda Martin PhD,Male,58421 Anita Ville Suite 720,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
89232,Christine Patel,Male,099 Landry Locks Suite 773,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
91419,Amber Miller,Female,958 Elizabeth Walks Apt. 578,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
92587,David Macdonald,Male,3075 Karen Villages,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
93695,Debra Evans,Female,347 Lewis Courts,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
94048,Alicia Cobb,Female,7040 Michael Circles,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
94501,John Miller,Male,6387 Murillo Knolls,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
94676,David Williams,Female,4743 Williams Hill Suite 727,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
98846,Bradley Lester,Female,9880 Amy Via Suite 042,Zimbabwean,Current,1,True,2,2,False,True,2,True,2
99185,Cassandra Morris,Male,54166 Nicholas Isle Apt. 439,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2
99870,Terry Allen,Female,587 Daugherty Prairie,Zimbabwean,Savings,1,True,2,2,False,True,2,True,2

In [151]:
# Print the DataFrame to csv file

df.to_csv('train_data.csv')